//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FridgyKey.DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class my_dbEntities1 : DbContext
    {
        public my_dbEntities1()
            : base("name=my_dbEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblBasket> tblBasket { get; set; }
        public virtual DbSet<tblFrost> tblFrost { get; set; }
        public virtual DbSet<tblHack> tblHack { get; set; }
        public virtual DbSet<tblKkal> tblKkal { get; set; }
        public virtual DbSet<tblRecipeIn> tblRecipeIn { get; set; }
        public virtual DbSet<tblRecipeMain> tblRecipeMain { get; set; }
        public virtual DbSet<tblSticker> tblSticker { get; set; }
        public virtual DbSet<tblUser> tblUser { get; set; }
    }
}
