//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FridgyKey.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSticker
    {
        public int Id { get; set; }
        public Nullable<int> userID { get; set; }
        public string text { get; set; }
        public Nullable<int> frostID { get; set; }
    
        public virtual tblUser tblUser { get; set; }
    }
}
